# Add this new file to your deployment
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
  namespace: default
  annotations:
    azure.workload.identity/client-id: "2264dfb6-3242-495c-ba41-4484b92aeeff"
  labels:
    azure.workload.identity/use: "true"
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: makeline-service
  namespace: default
  annotations:
    azure.workload.identity/client-id: "2264dfb6-3242-495c-ba41-4484b92aeeff"
  labels:
    azure.workload.identity/use: "true"
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: blob-connector-service
  namespace: default
  annotations:
    azure.workload.identity/client-id: "92482939-2a16-4634-adcc-02f9496ee4d6"
  labels:
    azure.workload.identity/use: "true"
---

# StatefulSet for MongoDB
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb # Associated headless service for DNS resolution
  replicas: 3 # Number of MongoDB replicas
  selector:
    matchLabels:
      app: mongodb # Labels to match for this StatefulSet
  template:
    metadata:
      labels:
        app: mongodb # Pod label for identification
    spec:
      nodeSelector:
        "kubernetes.io/os": linux # Run only on Linux nodes
      containers:
        - name: mongodb
          image: mongo:4.2 # MongoDB container image version
          ports:
            - containerPort: 27017 # Default MongoDB port
              name: mongodb
          resources: # Resource requests and limits for MongoDB
            requests:
              cpu: 5m # Minimum CPU
              memory: 75Mi # Minimum Memory
            limits:
              cpu: 25m # Maximum CPU
              memory: 1024Mi # Maximum Memory
          livenessProbe: # Probe to check MongoDB health
            exec:
              command:
                - mongosh
                - --eval
                - db.runCommand('ping').ok
            initialDelaySeconds: 5 # Wait time before starting probe
            periodSeconds: 5 # Interval between probes
          command: # Claude was used to help add the replication code into the deployment file. 
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip_all"
            - "--dbpath"
            - /data/db

          volumeMounts:
            - name: mongodb 
              mountPath: /data/db
        - name: rs-init
          image: mongo:4.2
          command:
            - bash
            - -c
            - |
              if [ "$MY_POD_NAME" != "mongodb-0" ]; then
                sleep infinity
              fi
              until mongo  --host localhost:27017 --eval "db.adminCommand('ping')" &>/dev/null; do
                sleep 5
              done
              RS_STATUS=$(mongo  --host localhost:27017 --eval \
                "JSON.stringify(rs.status().ok)" --quiet 2>/dev/null || echo "0")
              if [ "$RS_STATUS" = "1" ]; then
                echo "Already initialised"
              else
                mongo  --host localhost:27017 --eval '
                  rs.initiate({
                    _id: "rs0",
                    members: [
                      { _id: 0, host: "mongodb-0.mongodb:27017" },
                      { _id: 1, host: "mongodb-1.mongodb:27017" },
                      { _id: 2, host: "mongodb-2.mongodb:27017" }
                    ]
                  })
                '
              fi
              sleep infinity
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
  volumeClaimTemplates:
    - metadata:
        name: mongodb
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
# Service to expose MongoDB
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  clusterIP: None # Internal cluster service
  ports:
    - port: 27017 # MongoDB service port
  selector:
    app: mongodb # Target pods with label `app: mongodb`
---
# Deployment for Order Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1 # Single replica
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: order-service 
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: order-service
          image: jchen1101/fp-order-service:latest # Custom image for order service
          ports:
            - containerPort: 3000 # Order service listens on this port
          env: # Environment variables for configuration
            - name: USE_WORKLOAD_IDENTITY_AUTH
              value: "true"
            - name: ORDER_QUEUE_HOSTNAME
              value: "cst8915final-project-bus.servicebus.windows.net"
            - name: ORDER_QUEUE_NAME
              value: "orders"
            - name: FASTIFY_ADDRESS
              value: "0.0.0.0"
          resources: # Resource allocation
            requests:
              cpu: 1m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 256Mi
          startupProbe: # Initial health check
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe: # Ready status probe
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe: # Ongoing health check
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 3     
---
# Service for Order Service
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: order-service
---
# Deployment for Makeline Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makeline-service
spec:
  replicas: 1 # Single replica
  selector:
    matchLabels:
      app: makeline-service
  template:
    metadata:
      labels:
        app: makeline-service
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: makeline-service 
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: makeline-service
          image: jchen1101/fp-makeline-service:latest # Custom Makeline service image
          ports:
            - containerPort: 3001 # Makeline service listens on this port
          env: # Environment variables for configuration
            - name: USE_WORKLOAD_IDENTITY_AUTH
              value: "true"
            - name: ORDER_QUEUE_HOSTNAME
              value: "cst8915final-project-bus.servicebus.windows.net"
            - name: ORDER_QUEUE_NAME
              value: "orders"
            - name: ORDER_DB_URI
              value: "mongodb://mongodb-0.mongodb:27017,mongodb-1.mongodb:27017,mongodb-2.mongodb:27017/?replicaSet=rs0" # MongoDB connection string
            - name: ORDER_DB_NAME
              value: "orderdb" # Database name
            - name: ORDER_DB_COLLECTION_NAME
              value: "orders" # Collection name
          resources: # Resource requests and limits
            requests: # claude was used to help debug the issue of makeline not deploying
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 128Mi
          startupProbe: # Initial health check
            httpGet:
              path: /health
              port: 3001
            failureThreshold: 10
            periodSeconds: 5
          readinessProbe: # Ready status probe
            httpGet:
              path: /health
              port: 3001
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe: # Ongoing health check
            httpGet:
              path: /health
              port: 3001
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 3
---
# Service for Makeline Service
apiVersion: v1
kind: Service
metadata:
  name: makeline-service
spec:
  type: ClusterIP # Internal cluster service
  ports:
    - name: http
      port: 3001 # Service port
      targetPort: 3001
  selector:
    app: makeline-service
---
# Deployment for Product Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1 # Single replica
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: product-service
          image: jchen1101/fp-product-service:latest # Custom product service image
          ports:
            - containerPort: 3002 # Product service listens on this port
          env: # Environment variables for configuration
            - name: AI_SERVICE_URL
              value: "http://ai-service:5001/" # URL for AI service integration
          resources: # Resource requests and limits
            requests:
              cpu: 1m
              memory: 1Mi
            limits:
              cpu: 2m
              memory: 20Mi
          readinessProbe: # Ready status probe
            httpGet:
              path: /health
              port: 3002
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe: # Ongoing health check
            httpGet:
              path: /health
              port: 3002
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 3
---
# Service for Product Service
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3002 # Service port
      targetPort: 3002
  selector:
    app: product-service
---
# Deployment for Store Front
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-front
  template:
    metadata:
      labels:
        app: store-front
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: store-front
          image: jchen1101/fp-store-front:latest # Front-end store application
          ports:
            - containerPort: 8080 # Front-end app port
              name: store-front
          env: # Environment variables for backend URLs
            - name: VUE_APP_ORDER_SERVICE_URL
              value: "http://order-service:3000/"
            - name: VUE_APP_PRODUCT_SERVICE_URL
              value: "http://product-service:3002/"
          resources: # Resource requests and limits
            requests:
              cpu: 1m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe: # Initial health check
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe: # Ready status probe
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe: # Ongoing health check
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 3
---
# Service for Store Front
apiVersion: v1
kind: Service
metadata:
  name: store-front
spec:
  ports:
    - port: 80 # Service port exposed outside the cluster
      targetPort: 8080 # Target container port
  selector:
    app: store-front
  type: LoadBalancer # Expose service externally via load balancer
---
# Deployment for Store Admin
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-admin
  template:
    metadata:
      labels:
        app: store-admin
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: store-admin
          image: jchen1101/fp-store-admin:latest # Admin interface for store
          ports:
            - containerPort: 8081 # Admin app port
              name: store-admin
          env: # Environment variables for backend URLs
            - name: VUE_APP_PRODUCT_SERVICE_URL
              value: "http://product-service:3002/"
            - name: VUE_APP_MAKELINE_SERVICE_URL
              value: "http://makeline-service:3001/"
          resources: # Resource requests and limits
            requests:
              cpu: 1m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe: # Initial health check
            httpGet:
              path: /health
              port: 8081
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe: # Ready status probe
            httpGet:
              path: /health
              port: 8081
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe: # Ongoing health check
            httpGet:
              path: /health
              port: 8081
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 3
---
# Service for Store Admin
apiVersion: v1
kind: Service
metadata:
  name: store-admin
spec:
  ports:
    - port: 80 # Service port exposed outside the cluster
      targetPort: 8081
  selector:
    app: store-admin
  type: LoadBalancer # Expose service externally via load balancer
---
# Service for Blob Connector Service
apiVersion: v1
kind: Service
metadata:
  name: blob-connector-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3005
      targetPort: 3005
  selector:
    app: blob-connector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blob-connector
  template:
    metadata:
      labels:
        app: blob-connector
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: blob-connector-service
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: blob-connector
          image: jchen1101/fp-blob-connector:latest
          ports:
            - containerPort: 3005
              name: blob-connector
          env:
            - name: BLOB_ADDRESS
              value: "https://cst8915finalprojectblob.blob.core.windows.net/"
            - name: BLOB_CONTAINER
              value: "products"
          resources:
            requests:
              cpu: 1m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /health
              port: 3005
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3005
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3005
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 3
